name: continuous-integration
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: 
            - ubuntu-latest
            - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and Test
        run: make test
